export const BACKEND_DOMAIN_CONTRACTS = Object.freeze({
  user: { source: 'modules/user/domain/User.java', fields: ['id', 'email', 'isBanned', 'requestedAdmin', 'fullName', 'phoneNumber', 'instapayRefundPhoneNumber', 'instapayRefundName', 'birthday', 'addresses'], excluded: ['passwordHash'] },
  vendor: { source: 'modules/vendor/domain/Vendor.java', fields: ['userId', 'supplierId', 'storeName', 'description', 'logoUrl', 'bannerUrl', 'contactEmail', 'contactPhone', 'address', 'websiteUrl', 'instagramUrl', 'facebookUrl', 'workingHours', 'isVerified'] },
  product: { source: 'modules/product/domain/Product.java', fields: ['supplierId', 'id', 'name', 'description', 'price', 'pricingMode', 'currentCommissionRate', 'details', 'status', 'createdAt', 'updatedAt', 'publishedAt', 'reviewRequestStatus', 'reviewRequestedFromStatus', 'reviewRequestedAt', 'reviewReviewedAt', 'reviewedBy', 'reviewRequestMessage', 'reviewRejectionReason', 'averageRating', 'reviewCount', 'stockQuantity', 'discountPercentage', 'discountStartDate', 'discountEndDate', 'categories', 'images'] },
  order: { source: 'modules/order/domain/Order.java', fields: ['id', 'customerId', 'guestInfo', 'status', 'items', 'totalAmount', 'placedAt', 'shippingAddress', 'paymentMethod', 'customerName', 'customerEmail', 'customerPhone', 'instapayPhoneNumber', 'instapayRefundPhoneNumber', 'instapayRefundName', 'deliveryZoneId', 'deliveryCost', 'deliveryCostBreakdown', 'estimatedDeliveryDate', 'actualDeliveryDate', 'deliveryNotes', 'commissionPaid', 'commissionPaidAt', 'instapayTransactionIds', 'instapayPaymentMessages', 'paymentMethodLockedAt', 'paymentConfirmedAt', 'paymentConfirmedBy', 'paymentRejectionReason', 'vendorStatuses', 'vendorCompletedAt', 'vendorFinancialReleaseAt', 'commissionRates', 'vendorSubtotals', 'vendorCommissionAmounts', 'commissionRatesSnapshottedAt', 'vendorInvalidatedAt', 'vendorInvalidatedBy', 'vendorInvalidationReasons', 'vendorInvalidationDetails'] },
  giftFlow: { source: 'modules/flow/domain/GiftFlow.java', fields: ['id', 'supplierId', 'name', 'description', 'configuration', 'imageUrl', 'createdAt', 'updatedAt'] },
  cart: { source: 'modules/cart/domain/Cart.java', fields: ['id', 'customerId', 'items', 'updatedAt'] },
  review: { source: 'modules/review/domain/Review.java', fields: ['id', 'userId', 'reviewType', 'entityId', 'rating', 'comment', 'status', 'createdAt', 'reviewedAt', 'reviewedBy', 'moderatorNotes', 'isAnonymous', 'contentScore', 'orderId'] },
  category: { source: 'modules/category/domain/Category.java', fields: ['id', 'categoryId', 'categoryName', 'name', 'products'], aliases: { categoryId: 'id', categoryName: 'name', products: 'relations.products' } },
  vendorApplication: { source: 'modules/vendor/domain/VendorApplication.java', fields: ['id', 'userId', 'storeName', 'description', 'logoUrl', 'bannerUrl', 'contactEmail', 'contactPhone', 'address', 'websiteUrl', 'instagramUrl', 'facebookUrl', 'workingHours', 'status', 'submittedAt', 'reviewedAt', 'reviewedBy', 'rejectionReason'] },
  commission: { source: 'modules/commission/domain/Commission.java', fields: ['id', 'orderId', 'supplierId', 'orderSubtotal', 'commissionRate', 'commissionAmount', 'payableAmount', 'direction', 'status', 'dueDate', 'paidAt', 'createdAt'] },
  commissionPaymentRequest: { source: 'modules/commission/domain/CommissionPaymentRequest.java', fields: ['id', 'commissionId', 'supplierId', 'message', 'proofImageUrl', 'messages', 'status', 'submittedAt', 'reviewedAt', 'reviewedBy', 'rejectionReason'] },
  commissionRule: { source: 'modules/commission/domain/CommissionRule.java', fields: ['id', 'type', 'supplierId', 'rate', 'startDate', 'endDate', 'active', 'createdAt', 'createdBy'] },
  report: { source: 'modules/report/domain/Report.java', fields: ['id', 'reporterId', 'reportType', 'reportedEntityId', 'reason', 'description', 'status', 'createdAt', 'reviewedAt', 'reviewedBy', 'adminNotes', 'outcomeType', 'outcomeAction'] },
  adminRequest: { source: 'modules/admin/domain/AdminRequest.java', fields: ['id', 'userId', 'message', 'status', 'requestedAt', 'reviewedAt', 'reviewedBy', 'reviewNotes', 'canReapplyAt'] },
  orderAssistance: { source: 'modules/commission/domain/OrderAssistanceRequest.java', fields: ['id', 'orderId', 'supplierId', 'message', 'status', 'requestedAt', 'resolvedAt', 'resolvedBy', 'resolution'] },
  notification: { source: 'modules/notification/domain/Notification.java', fields: ['id', 'userId', 'title', 'message', 'type', 'read', 'createdAt', 'metadata'] },
  vendorFeedback: { source: 'modules/review/domain/VendorFeedback.java', fields: ['id', 'userId', 'vendorId', 'orderId', 'feedback', 'status', 'createdAt', 'reviewedAt', 'reviewedBy', 'moderatorNotes', 'contentScore'] },
  deliveryZone: { source: 'modules/delivery/domain/DeliveryZone.java', fields: ['id', 'zoneName', 'description', 'isActive'] },
  vendorDeliveryPricing: { source: 'modules/delivery/domain/VendorDeliveryPricing.java', fields: ['vendorId', 'zoneId', 'deliveryCost', 'updatedAt'] },
  reminder: { source: 'modules/reminder/domain/Reminder.java', fields: ['id', 'customerId', 'description', 'scheduledAt', 'processed'] },
  vendorActivity: { source: 'modules/vendor/domain/VendorActivity.java', fields: ['id', 'vendorId', 'activityType', 'description', 'relatedEntityId', 'metadata', 'occurredAt'] },
  userReviewRestriction: { source: 'modules/review/domain/UserReviewRestriction.java', fields: ['userId', 'canComment', 'canReview', 'restrictedAt', 'restrictedBy', 'reason', 'expiresAt'] },
  favorite: { source: 'modules/user/domain/FavoriteProduct.java', fields: ['id', 'userId', 'productId', 'flowId', 'addedAt'] },
});

export const BACKEND_EMBEDDED_CONTRACTS = Object.freeze({
  address: { source: 'modules/user/domain/Address.java', fields: ['label', 'street', 'city', 'state', 'zipCode', 'country', 'isDefault'] },
  adminFacet: { source: 'modules/admin/domain/Admin.java', fields: ['userId', 'permissions'] },
  productDetails: { source: 'modules/product/domain/ProductDetails.java' },
  productImage: { source: 'modules/product/domain/ProductImage.java', fields: ['id', 'productId', 'url', 'primary', 'displayOrder'] },
  orderItem: { source: 'modules/order/domain/OrderItem.java', fields: ['productId', 'productName', 'imageUrl', 'quantity', 'price', 'supplierId', 'groupId', 'metadata'] },
  guestInfo: { source: 'modules/order/domain/GuestInfo.java', fields: ['email', 'firstName', 'lastName', 'phone', 'shippingAddress'] },
  cartItem: { source: 'modules/cart/domain/CartItem.java', fields: ['productId', 'quantity', 'groupId', 'metadata'] },
  orderAssistanceMessage: { source: 'modules/commission/domain/OrderAssistanceMessage.java', fields: ['id', 'requestId', 'senderId', 'senderRole', 'message', 'createdAt'] },
  vendorDeliveryPricingId: { source: 'modules/delivery/domain/VendorDeliveryPricingId.java', fields: ['vendorId', 'zoneId'] },
});

export const BACKEND_ENUM_CONTRACTS = Object.freeze({
  productStatus: ['modules/product/domain/ProductStatus.java', ['DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'DISABLED']],
  productReviewRequestStatus: ['modules/product/domain/ProductReviewRequestStatus.java', ['PENDING', 'APPROVED', 'REJECTED']],
  targetGender: ['modules/product/domain/TargetGender.java', ['MALE', 'FEMALE', 'UNISEX', 'CHILD']],
  vendorPricingMode: ['common/pricing/VendorPricingMode.java', ['CUSTOMER_PRICE', 'GUARANTEED_VENDOR_PAYOUT']],
  orderStatus: ['modules/order/domain/OrderStatus.java', ['PENDING_CONFIRMATION', 'IN_PROGRESS', 'OUT_FOR_DELIVERY', 'DONE', 'INVALID', 'PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED']],
  reviewStatus: ['modules/review/domain/ReviewStatus.java', ['APPROVED', 'PENDING_REVIEW', 'REJECTED']],
  reviewType: ['modules/review/domain/ReviewType.java', ['PRODUCT', 'VENDOR']],
  vendorApplicationStatus: ['modules/vendor/domain/VendorApplicationStatus.java', ['PENDING', 'APPROVED', 'REJECTED']],
  adminRequestStatus: ['modules/admin/domain/AdminRequestStatus.java', ['PENDING', 'APPROVED', 'REJECTED', 'INVALIDATED']],
  commissionStatus: ['modules/commission/domain/CommissionStatus.java', ['PENDING', 'PAYMENT_SUBMITTED', 'PAID', 'OVERDUE']],
  paymentRequestStatus: ['modules/commission/domain/PaymentRequestStatus.java', ['PENDING', 'APPROVED', 'REJECTED']],
  ruleType: ['modules/commission/domain/RuleType.java', ['GLOBAL', 'SUPPLIER_SPECIFIC']],
  assistanceStatus: ['modules/commission/domain/AssistanceStatus.java', ['PENDING', 'IN_PROGRESS', 'RESOLVED', 'CLOSED']],
  assistanceSender: ['modules/commission/domain/AssistanceSenderRole.java', ['VENDOR', 'ADMIN']],
  reportStatus: ['modules/report/domain/ReportStatus.java', ['PENDING', 'UNDER_REVIEW', 'ACTION_TAKEN', 'DISMISSED', 'RESOLVED']],
  reportType: ['modules/report/domain/ReportType.java', ['PRODUCT', 'GIFT_FLOW', 'USER', 'VENDOR', 'ADMIN']],
  reportOutcomeType: ['modules/report/domain/ReportOutcomeType.java', ['RESOLVED', 'ACTION_TAKEN']],
  notificationType: ['modules/notification/domain/NotificationType.java', ['ORDER_STATUS_UPDATE', 'PROMOTION', 'REMINDER', 'VENDOR_ALERT', 'SYSTEM_ALERT', 'REVIEW_REQUEST', 'DELIVERY_DELAY', 'DELIVERY_ESTIMATE_UPDATE']],
  vendorActivityType: ['modules/vendor/domain/VendorActivityType.java', ['ORDER_RECEIVED', 'ORDER_SHIPPED', 'ORDER_DELIVERED', 'ORDER_CANCELLED', 'PRODUCT_CREATED', 'PRODUCT_UPDATED', 'PRODUCT_APPROVED', 'PRODUCT_REJECTED', 'PRODUCT_STOCK_UPDATED', 'PRODUCT_OUT_OF_STOCK', 'REVIEW_RECEIVED', 'FEEDBACK_RECEIVED', 'DELIVERY_PRICING_UPDATED', 'GIFT_FLOW_CREATED', 'GIFT_FLOW_UPDATED']],
});
