export const ADMIN_PERMISSIONS = Object.freeze([
  'VIEW_USERS', 'MANAGE_USERS', 'DELETE_USERS', 'BAN_USERS', 'UNBAN_USERS',
  'REVIEW_ADMIN_REQUESTS', 'MAKE_ADMINS', 'DEMOTE_ADMINS',
  'MANAGE_ADMIN_PERMISSIONS', 'MAKE_VENDORS', 'ACTIVATE_VENDORS',
  'DEACTIVATE_VENDORS', 'ACTIVATE_PRODUCTS', 'REJECT_PRODUCTS',
  'DEACTIVATE_PRODUCTS', 'DELETE_PRODUCTS', 'MANAGE_CATEGORIES', 'VIEW_ORDERS',
  'MANAGE_ORDERS', 'MANAGE_ORDER_STATUS', 'REVIEW_ORDER_ASSISTANCE',
  'CONFIRM_ORDER_PAYMENTS',
  'VIEW_FINANCIAL_DATA', 'MANAGE_COMMISSIONS', 'REVIEW_COMMISSION_PAYMENTS',
  'URGE_COMMISSION_PAYMENT', 'VIEW_FINANCIAL_ANALYTICS', 'MANAGE_GIFT_FLOWS',
  'MANAGE_VENDOR_PAYOUTS',
  'SEND_NOTIFICATIONS', 'MANAGE_REPORTS', 'VIEW_REVIEWS', 'MODERATE_REVIEWS',
  'VIEW_VENDOR_FEEDBACK', 'MUTE_USERS', 'SUPER_ADMIN',
]);

export const ADMIN_PERMISSION_SET = new Set(ADMIN_PERMISSIONS);
